version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dependency-updates
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.5
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
    - 24.3.6
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
