include:
  - remote: https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/Scan/npm.yml
  - remote: https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/license_management.yml
  - remote: https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/js_common.yml

stages:
  - test
  - scan
  - deploy

test:
  extends: .npm:test

scan:
  extends: .scan:npm

deploy:
  extends: .npm:deploy
